name: example-environment

dependencies:
  - python=2.7
  - numpy
  - scipy
  - statsmodels
  - pandas
  - matplotlib
  - seaborn
  - openpyxl
  - future
  - ipywidgets
  - pytz
  - six
  - python-dateutil
  - scikit-image
  - pip:
    - argh
    - qgrid

